services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: OrderManagementDb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 5s
      timeout: 10s
      retries: 5

  api:
    build: .
    container_name: ordermanagement-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDB=mongodb://mongodb:27017
    ports:
      - "8080:8080"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
